spring:
  data:
    mongodb:
      uri: mongodb+srv://kimttang:admin@project-chat.aara4rr.mongodb.net/chat?retryWrites=true&w=majority&appName=project-chat
      #MongoDB 주소 및 DB 이름

file:
  upload-dir: ./uploads # 프로젝트 루트 폴더 아래에 uploads 폴더를 사용

ollama:
  base-url: https://ollama-service-992949675273.us-central1.run.app
  model: gemma3:4b